blog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views

urlpatterns = [
   
    path('', views.home, name='home'),
    path('addpost', views.addpost, name="addpost"),

    path('post/<int:pk>', views.single_post, name="single_post"),
    path('search', views.search, name="search_text"),
    # path('addprofile', views.addprofile, name="addprofile"),
    path('signup', views.signup, name="signup"),
    path('login', views.login_, name="login"),
    path('profile/<int:pk>', views.profile, name="profile"),
    path('edit_post/<int:pk>', views.edit_post, name="edit_post"),
    path('edit_profile/<int:pk>', views.edit_profile, name="edit_profile"),
    path('log_out', views.log_out, name="log_out"),
    path('delete', views.delete, name="delete"),
    path('delete_post/<int:pk>', views.delete_post, name="delete_post"),
    # path('forgot_pass', views.forgot_pass, name="forgot_pass")
]

tut1/urls.py
from django.contrib import admin
from django.urls import path,include
#from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import *

# Create your models here.
class Profile(models.Model):
    name = models.CharField(max_length=300)
    occupation = models.TextField(blank=True, null=True)
    time = models.DateTimeField(auto_now_add=True)
    dp = models.ImageField(upload_to = 'dp', null= True, blank=True, default='/dp/luna.jpg')
    prof_user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.prof_user.username) + " " + str(self.name)


class Post(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    image = models.ImageField(upload_to = 'post', null= True, blank=True)
    def __str__(self):
        return str(self.title) + " " + str(self.author)



def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(prof_user=instance)

post_save.connect(create_user_profile, sender=User)   

       

blog/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import Http404
from . models import Post
from . models import Profile

from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required


# Create your views here.
def home(request):

    profiles = Profile.objects.all().order_by("-time")
    posts = Post.objects.all().order_by("-time")
    context = {
        "posts":posts,
        "profiles":profiles,
    }
    print(posts)
    return render(request,'home.html', context)

@login_required(login_url='signup')    
def addpost(request):
    if request.method =="POST":
        title =  request.POST.get('title','')
        description = request.POST.get('description','')



        thumb =  request.FILES.get('thumbnail','')
        prof = Profile.objects.filter(prof_user=request.user)[0]

        post_blog = Post(title=title, description=description, image=thumb, author=prof)



        post_blog.save()
        messages.success(request,"Thanks For Posting")

    return render(request,"addpost.html")    

def single_post(request, pk):
    single_post=Post.objects.filter(pk=pk)[0]
    context={
        "post":single_post
    }
    return render(request,"single_post.html", context)

def search(request):
    if request.method =="POST":

        search_text=request.POST.get('search_text','')
        print(search_text)

        allpost_title = Post.objects.filter(title__icontains = search_text)
        allpost_content = Post.objects.filter(description__icontains = search_text)
        allposts = allpost_title.union(allpost_content)

        context={
            "txt":search_text,
            "search_post":allposts

        }


        return render(request, 'search.html', context)

    else:
        raise Http404()        

# def addprofile(request):
#     if request.method=="POST":
#         name = request.POST.get('name','')
#         about = request.POST.get('about','')
#         print(name)
#         print(about)

#         dp=request.FILES.get('dp','')
#         profl = Post(title=name, description=about, image=dp)
#         profl.save()
#         messages.success(request,"Account has been created")

#     return render(request,"addprofile.html")    

def signup(request):
    if request.method =="POST":
        name =  request.POST.get('name','')
        username = request.POST.get('username','')
        email =  request.POST.get('email','')
        password = request.POST.get('password','')
        confpassword = request.POST.get('confpassword','')
        userCheck = User.objects.filter(username=username)
        if len(username)>20:
            messages.warning(request,"Too Long Username!!")
        elif password != confpassword:
            messages.warning(request,"Passwords Don't Match!!")    
        elif userCheck:
            messages.warning(request,"Username Already Exist, Kindly Change!!")   
        else:
            user_obj = User.objects.create_user(first_name=name, email=email, password=password, username=username)
            user_obj.save()
            messages.success(request,"Account Created Successfully!!")

    return render(request,"signup.html")    

def login_(request):
    if request.method =="POST":

        username = request.POST.get('username','')
        password = request.POST.get('password','')
        print(username)
        print(password)
        user_obj = authenticate(username=username, password=password)
        user_obj2 = User.objects.filter(username=username)[0]
        if user_obj is not None:
            login(request, user_obj)
            # messages.success(request,"Logged In Successfully:^) ")
            return redirect('/profile/' + str(user_obj2.pk))
        else:
            messages.warning(request,"Invalid Credentials : ( ") 
            return redirect('/signup')
    else:
        return render(request, "signup.html")

@login_required(login_url='signup') 
def profile(request, pk):
    prof = Profile.objects.filter(pk=pk)[0]
    posts = Post.objects.filter(author=prof).order_by("-time")
    postno = len(posts)
    context={
        "prof":prof,
        "posts":posts,
        "postno":postno
        
    }
    return render(request,"profile.html", context)

def edit_post(request, pk): 
    pos=Post.objects.filter(pk=pk)[0]
    context={
        'i':pos
    }
    if pos.author.prof_user==request.user:
        if request.method=="POST":
            title = request.POST.get('title','') 
            description = request.POST.get('description','')
            image =  request.FILES.get('thumbnail','')
            if title:
               pos.title=title
            if description:   
               pos.description=description
            if image:
                pos.image=image   

            pos.save()
            return redirect('/profile/' + str(request.user.pk))
        return render(request,"edit_post.html", context) 
    else:
        raise Http404()

@login_required(login_url='signup')
def edit_profile(request, pk): 
    prf=Profile.objects.filter(pk=pk)[0]
    context={
        'i':prf
    }
    if prf.prof_user==request.user:
        if request.method=="POST":

            about = request.POST.get('about','')
            prfp =  request.FILES.get('prfp','')
            if about:
                prf.occupation=about
            
            if prfp:
                prf.dp=prfp
   
    

            prf.save()
            return redirect('/profile/' + str(request.user.pk))   
        return render(request,"edit_profile.html", context) 
    else:
        raise Http404()        

def log_out(request):
    logout(request)

    return redirect("/")

def delete(request):
    
    user = request.user
    user.delete()

    return redirect("/")    
  
# def forgot_pass(request):

def delete_post(request, pk):
    pos=Post.objects.filter(pk=pk)[0]

    context={
        'i':pos
    }
    if pos.author.prof_user==request.user:
        pos.delete()
        return redirect('/profile/' + str(request.user.pk))
 

templates/addpost.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Post</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

</head>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Bitter:wght@500&family=Josefin+Sans:wght@300;400;600;700&family=Poppins:wght@600;800&display=swap');
  * {
        margin: 0;
        padding: 0;
        font-family: 'Bitter', sans-serif;
    }
    </style>
<body>

  <!-- nav bar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="padding-top: 20px;padding-bottom: 20px; color: black;">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" style="font-size: 18px; padding-left: 60px;"
              href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" style="font-size: 18px; padding-left: 60px;" href="{% url 'addpost' %}">Add Post</a>
          </li>




          <!-- {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" style="font-size: 18px;" href="{% url 'profile' request.user.profile_set.first.pk %}"
              tabindex="-1">{{request.user.username}}</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link btn btn-outline-info" style="font-size: 18px;" href="{% url 'signup' %}">Sign Up</a>
          </li>
          {% endif %}

          {% if request.user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link btn btn-outline-info" style="font-size: 18px;" href="{% url 'log_out' %}">Log Out</a>
          </li>

          <li class="nav-item">
            <a class="nav-link btn btn-outline-info" style="font-size: 18px;" href="{% url 'delete' %}">Delete Account</a>
          </li>

          {% endif %} -->


          {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false" style="font-size: 18px; padding-left: 60px;">
              {{request.user.username}}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" style="font-size: 16px;"
                  href="{% url 'profile' request.user.profile_set.first.pk %}">
                  View Profile</a></li>
              <li><a class="dropdown-item" style="font-size: 16px;" href="{% url 'log_out' %}">Log Out</a></li>

              <li><a class="dropdown-item" style="font-size: 16px;" data-bs-toggle="modal"
                  data-bs-target="#exampleModal">Delete Account</a></li>

            </ul>
          </li>
          {% else %}
          <li class="nav-item" style="padding-left: 60px;">
            <a class="nav-link" style="font-size: 18px;" href="{% url 'signup' %}">Sign Up</a>
          </li>
          {% endif %}

        </ul>

        <form method="POST" action="{% url 'search_text' %}" class="d-flex">{% csrf_token %}
          <input class="form-control me-2" type="text" name="search_text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-info" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

    <!-- form -->

    <div class="container mt-3">

        <form enctype="multipart/form-data" method="POST" action="{% url 'addpost' %}" class="row g-3">{% csrf_token %}
            <div class="col-md-6 mb-3" style="padding-top: 30px;">
                <label for="inputEmail4" class="form-label" style="font-size: 19px;">Title</label>
                <input type="text" name="title" class="form-control" id="inputEmail4">
            </div>
     


            <div class="md-6 mb-3">
                <label for="formFile" class="form-label" style="font-size: 19px;">Thumbnail</label>
                <input class="form-control" name="thumbnail" type="file" id="formFile">
              </div>

            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label" style="font-size: 19px;">Description</label>
                <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3"></textarea>
              </div>
       
            <div class="col-12"  style="padding-top: 50px; ">
                <center><button type="submit" class="btn btn-primary" style="font-size: 20px; width:100px; font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif">Post</button></center>
            </div>
        </form>

        {% if messages %}

        {% for i in messages %}

        <div class="alert alert-{{i.tags}}" role="alert">
        {{i}}
        </div>

        {% endfor %}

        {% endif %}



    </div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">

      <div class="modal-content">



        <div class="modal-body">
          <div class="container">
            <!-- form -->
            <div class="container mt-4">
              <form enctype="multipart/form-data" method="POST" action="{% url 'delete' %}">{% csrf_token %}

          
                <center><p style="font-size: 19px;">Are you sure you want to delete your account ?</p></center>

                <br>
                <center><button type="submit" class="btn btn-dark">Delete</button>
                  <button type="button" class="btn btn-info" data-bs-dismiss="modal">Cancel</button>
                </center>
              
              </form>


              

            </div>

          </div>
        </div>

        
      </div>
    </div>
  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>

</body>

</html>

templates/edit_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

</head>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Bitter:wght@500&family=Josefin+Sans:wght@300;400;600;700&family=Poppins:wght@600;800&display=swap');
  * {
        margin: 0;
        padding: 0;
        font-family: 'Bitter', sans-serif;
    }
    </style>
<body>
  <!-- nav bar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="padding-top: 20px;padding-bottom: 20px; color: black;">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" style="font-size: 18px; padding-left: 60px;"
              href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="font-size: 18px; padding-left: 60px;" href="{% url 'addpost' %}">Add Post</a>
          </li>




          <!-- {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" style="font-size: 18px;" href="{% url 'profile' request.user.profile_set.first.pk %}"
              tabindex="-1">{{request.user.username}}</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link btn btn-outline-info" style="font-size: 18px;" href="{% url 'signup' %}">Sign Up</a>
          </li>
          {% endif %}

          {% if request.user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link btn btn-outline-info" style="font-size: 18px;" href="{% url 'log_out' %}">Log Out</a>
          </li>

          <li class="nav-item">
            <a class="nav-link btn btn-outline-info" style="font-size: 18px;" href="{% url 'delete' %}">Delete Account</a>
          </li>

          {% endif %} -->


          {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false" style="font-size: 18px; padding-left: 60px;">
              {{request.user.username}}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" style="font-size: 16px;"
                  href="{% url 'profile' request.user.profile_set.first.pk %}">
                  View Profile</a></li>
              <li><a class="dropdown-item" style="font-size: 16px;" href="{% url 'log_out' %}">Log Out</a></li>

              <li><a class="dropdown-item" style="font-size: 16px;" data-bs-toggle="modal"
                  data-bs-target="#exampleModal">Delete Account</a></li>

            </ul>
          </li>
          {% else %}
          <li class="nav-item" style="padding-left: 60px;">
            <a class="nav-link" style="font-size: 18px;" href="{% url 'signup' %}">Sign Up</a>
          </li>
          {% endif %}

        </ul>

        <form method="POST" action="{% url 'search_text' %}" class="d-flex">{% csrf_token %}
          <input class="form-control me-2" type="text" name="search_text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-info" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>


            <!-- form -->

    <div class="container mt-3">

        <form enctype="multipart/form-data" method="POST" action="{% url 'edit_post' i.pk %}" class="row g-3">{% csrf_token %}
            <div class="col-md-6 mb-3" style="padding-top: 30px;">
                <label for="inputEmail4" class="form-label" style="font-size: 19px;">Title</label>
                <input type="text" name="title" class="form-control" id="inputEmail4">
            </div>
     
  

            <div class="md-6 mb-3">
                <label for="formFile" class="form-label" style="font-size: 19px;">Image</label>
                <input class="form-control" name="thumbnail" type="file" id="formFile">
              </div>

            <div class="mb-3">
                <label for="exampleFormControlTextarea1" class="form-label" style="font-size: 19px;">Description</label>
                <textarea class="form-control" name="description" id="exampleFormControlTextarea1" rows="3"></textarea>
              </div>
       
            <div class="col-12"  style="padding-top: 50px; ">
                <center><button type="submit" class="btn btn-primary" style="font-size: 19px; width:100px; font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif">EDIT</button></center>
            </div>
        </form>





    </div>
    

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">

      <div class="modal-content">



        <div class="modal-body">
          <div class="container">
            <!-- form -->
            <div class="container mt-4">
              <form enctype="multipart/form-data" method="POST" action="{% url 'delete' %}">{% csrf_token %}

          
                <center><p style="font-size: 19px;">Are you sure you want to delete your account ?</p></center>

                <br>
                <center><button type="submit" class="btn btn-dark">Delete</button>
                  <button type="button" class="btn btn-info" data-bs-dismiss="modal">Cancel</button>
                </center>
              
              </form>


              

            </div>

          </div>
        </div>

        
      </div>
    </div>
  </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
    crossorigin="anonymous"></script>

</body>
</html>

templates/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

</head>

<style>
    @import url('https://fonts.googleapis.com/css2?family=Bitter:wght@500&family=Josefin+Sans:wght@300;400;600;700&family=Poppins:wght@600;800&display=swap');
    * {
          margin: 0;
          padding: 0;
          font-family: 'Bitter', sans-serif;
      }
      </style>

<body>


  <!-- nav bar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="padding-top: 20px;padding-bottom: 20px; color: black;">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" style="font-size: 18px; padding-left: 60px;"
              href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="font-size: 18px; padding-left: 60px;" href="{% url 'addpost' %}">Add Post</a>
          </li>




          <!-- {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" style="font-size: 18px;" href="{% url 'profile' request.user.profile_set.first.pk %}"
              tabindex="-1">{{request.user.username}}</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link btn btn-outline-info" style="font-size: 18px;" href="{% url 'signup' %}">Sign Up</a>
          </li>
          {% endif %}

          {% if request.user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link btn btn-outline-info" style="font-size: 18px;" href="{% url 'log_out' %}">Log Out</a>
          </li>

          <li class="nav-item">
            <a class="nav-link btn btn-outline-info" style="font-size: 18px;" href="{% url 'delete' %}">Delete Account</a>
          </li>

          {% endif %} -->


          {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false" style="font-size: 18px; padding-left: 60px;">
              {{request.user.username}}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" style="font-size: 16px;"
                  href="{% url 'profile' request.user.profile_set.first.pk %}">
                  View Profile</a></li>
              <li><a class="dropdown-item" style="font-size: 16px;" href="{% url 'log_out' %}">Log Out</a></li>

              <li><a class="dropdown-item" style="font-size: 16px;" data-bs-toggle="modal"
                  data-bs-target="#exampleModal">Delete Account</a></li>

            </ul>
          </li>
          {% else %}
          <li class="nav-item" style="padding-left: 60px;">
            <a class="nav-link" style="font-size: 18px;" href="{% url 'signup' %}">Sign Up</a>
          </li>
          {% endif %}

        </ul>

        <form method="POST" action="{% url 'search_text' %}" class="d-flex">{% csrf_token %}
          <input class="form-control me-2" type="text" name="search_text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-info" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

    <!-- form -->

    <div class="container mt-5">

        <form enctype="multipart/form-data" method="POST" action="{% url 'edit_profile' i.pk %}" class="row g-3">{% csrf_token %}


            <div class="col-12 md-6 mb-3">
                <label for="inputAddress" class="form-label" style="font-size: 18px;">About</label>
                <input type="text" name="about" class="form-control" id="inputAddress">
            </div>

            <div class="mb-3">
                <label for="formFile" class="form-label" style="font-size: 18px;">Profile Pic</label>
                <input class="form-control" name="prfp" type="file" id="formFile">
              </div>


            <div class="col-12" style="padding-top: 50px;">
                <center><button type="submit" class="btn btn-primary">EDIT</button></center>
            </div>
        </form>





    </div>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">

      <div class="modal-content">



        <div class="modal-body">
          <div class="container">
            <!-- form -->
            <div class="container mt-4">
              <form enctype="multipart/form-data" method="POST" action="{% url 'delete' %}">{% csrf_token %}

          
                <center><p style="font-size: 19px;">Are you sure you want to delete your account ?</p></center>

                <br>
                <center><button type="submit" class="btn btn-dark">Delete</button>
                  <button type="button" class="btn btn-info" data-bs-dismiss="modal">Cancel</button>
                </center>
              
              </form>


              

            </div>

          </div>
        </div>

        
      </div>
    </div>
  </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
    crossorigin="anonymous"></script>

</body>
</html>